name: Sync API Spec

on:
  repository_dispatch:
    types: [api_spec_updated]
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch OpenAPI spec from source repo
        run: |
          repo=${{ github.event.client_payload.spec_repo || 'j-shelfwood/obsidian-local-rest-api' }}
          path=${{ github.event.client_payload.spec_path || 'openapi.json' }}
          curl -sSL \
            -H "Accept: application/vnd.github.raw+json" \
            https://api.github.com/repos/${repo}/contents/${path} > openapi.json
          jq . openapi.json > /dev/null

      - name: Update working tree with new spec
        run: |
          mv openapi.json src/openapi.json

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Commit and push to main
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          if git diff --quiet --exit-code src/openapi.json; then
            echo "No changes to spec; skipping commit."
            exit 0
          fi
          git add src/openapi.json dist/openapi.json || true
          git commit -m "chore: sync API spec (scheduled or dispatch)"
          git push origin HEAD:main
